// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgzumixbpoeiwhqvscse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnenVtaXhicG9laXdocXZzY3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzQ3MjIsImV4cCI6MjA2MTgxMDcyMn0.GsLUnmpCoe25PyEsg-61e_Ka-W_9xapmwCrVC2BbDME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);